apiVersion: v1
kind: Pod
metadata:
  name: nginx-6
spec:
  containers:
  - name: nginx-1
    image: nginx
  - name: debian-2
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo test
          sleep 1;
        done
