apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-def
  labels:
    app: nginx-def
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-def
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-def
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

